name: credit-default-prediction
channels:
  - conda-forge
  - defaults
dependencies:
  - anyio=4.12.1
  - argon2-cffi=25.1.0
  - argon2-cffi-bindings=25.1.0
  - arrow=1.4.0
  - asttokens=3.0.1
  - async-lru=2.1.0
  - attrs=25.4.0
  - aws-c-auth=0.9.3
  - aws-c-cal=0.9.13
  - aws-c-common=0.12.6
  - aws-c-compression=0.3.1
  - aws-c-event-stream=0.5.7
  - aws-c-http=0.10.7
  - aws-c-io=0.23.3
  - aws-c-mqtt=0.13.3
  - aws-c-s3=0.11.3
  - aws-c-sdkutils=0.2.4
  - aws-checksums=0.2.7
  - aws-crt-cpp=0.35.4
  - aws-sdk-cpp=1.11.606
  - babel=2.17.0
  - backports.zstd=1.3.0
  - beautifulsoup4=4.14.3
  - bleach=6.3.0
  - bleach-with-css=6.3.0
  - brotli-python=1.2.0
  - bzip2=1.0.8
  - c-ares=1.34.6
  - ca-certificates=2026.1.4
  - cached-property=1.5.2
  - cached_property=1.5.2
  - certifi=2026.1.4
  - cffi=2.0.0
  - charset-normalizer=3.4.4
  - colorama=0.4.6
  - comm=0.2.3
  - debugpy=1.8.19
  - decorator=5.2.1
  - defusedxml=0.7.1
  - et_xmlfile=2.0.0
  - exceptiongroup=1.3.1
  - executing=2.2.1
  - expat=2.7.3
  - fqdn=1.5.1
  - h11=0.16.0
  - h2=4.3.0
  - hpack=4.1.0
  - httpcore=1.0.9
  - httpx=0.28.1
  - hyperframe=6.1.0
  - idna=3.11
  - importlib-metadata=8.7.0
  - ipykernel=7.1.0
  - ipython=9.9.0
  - ipython_pygments_lexers=1.1.1
  - isoduration=20.11.0
  - jedi=0.19.2
  - jinja2=3.1.6
  - json5=0.13.0
  - jsonpointer=3.0.0
  - jsonschema=4.26.0
  - jsonschema-specifications=2025.9.1
  - jsonschema-with-format-nongpl=4.26.0
  - jupyter-lsp=2.3.0
  - jupyter_client=8.8.0
  - jupyter_core=5.9.1
  - jupyter_events=0.12.0
  - jupyter_server=2.17.0
  - jupyter_server_terminals=0.5.4
  - jupyterlab=4.5.3
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.28.0
  - krb5=1.21.3
  - lark=1.3.1
  - libabseil=20250512.1
  - libarrow=23.0.0
  - libarrow-acero=23.0.0
  - libarrow-compute=23.0.0
  - libarrow-dataset=23.0.0
  - libarrow-substrait=23.0.0
  - libbrotlicommon=1.2.0
  - libbrotlidec=1.2.0
  - libbrotlienc=1.2.0
  - libcrc32c=1.1.2
  - libcurl=8.18.0
  - libevent=2.1.12
  - libexpat=2.7.3
  - libffi=3.4.4
  - libgoogle-cloud=2.39.0
  - libgoogle-cloud-storage=2.39.0
  - libgrpc=1.73.1
  - libparquet=23.0.0
  - libprotobuf=6.31.1
  - libre2-11=2025.11.05
  - libsodium=1.0.20
  - libssh2=1.11.1
  - libthrift=0.22.0
  - libutf8proc=2.11.3
  - libzlib=1.3.1
  - lz4-c=1.10.0
  - markupsafe=3.0.3
  - matplotlib-inline=0.2.1
  - mistune=3.2.0
  - nbclient=0.10.4
  - nbconvert-core=7.16.6
  - nbformat=5.10.4
  - nest-asyncio=1.6.0
  - notebook-shim=0.2.4
  - openpyxl=3.1.5
  - openssl=3.6.0
  - orc=2.2.2
  - overrides=7.7.0
  - packaging=26.0
  - pandocfilters=1.5.0
  - parso=0.8.5
  - pip=25.3
  - platformdirs=4.5.1
  - prometheus_client=0.24.1
  - prompt-toolkit=3.0.52
  - psutil=7.2.1
  - pure_eval=0.2.3
  - pyarrow-core=23.0.0
  - pycparser=2.22
  - pygments=2.19.2
  - pysocks=1.7.1
  - python=3.11.14
  - python-dateutil=2.9.0.post0
  - python-fastjsonschema=2.21.2
  - python-json-logger=2.0.7
  - python-tzdata=2025.3
  - python_abi=3.11
  - pytz=2025.2
  - pywin32=311
  - pywinpty=2.0.15
  - pyyaml=6.0.3
  - pyzmq=27.1.0
  - re2=2025.11.05
  - referencing=0.37.0
  - requests=2.32.5
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rfc3987-syntax=1.1.0
  - rpds-py=0.30.0
  - send2trash=2.1.0
  - setuptools=80.9.0
  - six=1.17.0
  - snappy=1.2.2
  - sniffio=1.3.1
  - soupsieve=2.8.3
  - sqlite=3.51.1
  - stack_data=0.6.3
  - terminado=0.18.1
  - tinycss2=1.5.1
  - tk=8.6.15
  - tomli=2.4.0
  - tornado=6.5.4
  - traitlets=5.14.3
  - typing-extensions=4.15.0
  - typing_extensions=4.15.0
  - typing_utils=0.1.0
  - tzdata=2025c
  - ucrt=10.0.22621.0
  - uri-template=1.3.0
  - urllib3=2.6.3
  - vc=14.3
  - vc14_runtime=14.44.35208
  - vs2015_runtime=14.44.35208
  - wcwidth=0.2.14
  - webcolors=25.10.0
  - webencodings=0.5.1
  - websocket-client=1.9.0
  - wheel=0.45.1
  - win_inet_pton=1.1.0
  - winpty=0.4.3
  - xz=5.6.4
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.23.0
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
      - absl-py==2.4.0
      - clarabel==0.11.1
      - cloudpickle==3.1.2
      - contourpy==1.3.3
      - credit-default-prediction==0.1.0
      - cvxpy==1.8.0
      - cycler==0.12.1
      - fonttools==4.61.1
      - future==1.0.0
      - highspy==1.12.0
      - hyperopt==0.2.7
      - imbalanced-learn==0.14.1
      - immutabledict==4.2.2
      - joblib==1.5.3
      - kiwisolver==1.4.9
      - lightgbm==4.6.0
      - llvmlite==0.46.0
      - matplotlib==3.10.8
      - networkx==3.6.1
      - numba==0.63.1
      - numpy==2.3.5
      - optbinning==0.21.0
      - ortools==9.11.4210
      - osqp==1.1.0
      - pandas==3.0.0
      - patsy==1.0.2
      - pillow==12.1.0
      - protobuf==5.26.1
      - py4j==0.10.9.9
      - pyarrow==23.0.0
      - pyparsing==3.3.2
      - ropwr==1.2.0
      - scikit-learn==1.8.0
      - scipy==1.17.0
      - scs==3.2.11
      - seaborn==0.13.2
      - shap==0.50.0
      - sklearn-compat==0.1.5
      - slicer==0.0.8
      - statsmodels==0.14.6
      - threadpoolctl==3.6.0
      - tqdm==4.67.1
      - xgboost==3.1.3
prefix: C:\Users\jooar\miniconda3\envs\credit-default-prediction
